insert into tags (slug, kind, name_en, name_ka, sort) values
  ('fine-line',  'style', 'Fine line',  'ფაინ ლაინი',    10),
  ('old-school', 'style', 'Old school', 'ოლდ სქული',      20),
  ('blackwork',  'style', 'Blackwork',  'ბლექვორქი',      30),
  ('japanese',   'style', 'Japanese',   'იაპონური',       40),
  ('realism',    'style', 'Realism',    'რეალიზმი',       50),
  ('dotwork',    'style', 'Dotwork',    'დოთვორქი',       60),
  ('watercolor', 'style', 'Watercolor', 'აკვარელი',       70),
  ('lettering',  'style', 'Lettering',  'ლეტერინგი',      80),
  ('traveler',   'vibe',  'Traveler',   'მოგზაური',       10),
  ('nature',     'vibe',  'Nature',     'ბუნება',         20),
  ('floral',     'vibe',  'Floral',     'ყვავილები',      30),
  ('animals',    'vibe',  'Animals',    'ცხოველები',      40),
  ('minimal',    'vibe',  'Minimal',    'მინიმალისტური',  50),
  ('dark',       'vibe',  'Dark',       'ბნელი',          60),
  ('geometric',  'vibe',  'Geometric',  'გეომეტრიული',    70),
  ('mythology',  'vibe',  'Mythology',  'მითოლოგია',      80),
  ('georgian',   'vibe',  'Georgian',   'ქართული',        90),
  ('portrait',   'vibe',  'Portrait',   'პორტრეტი',      100),
  ('script',     'vibe',  'Script',     'წარწერა',       110);
